FROM python:3.9
WORKDIR /code
COPY ./requirements.txt /code/requirements.txt
RUN pip install --no-cache-dir --upgrade -r /code/requirements.txt
COPY ./src /code/src
COPY ./app.py /code/app.py
COPY ./models /code/models
CMD ["uvicorn", "app:app", "--host", "0.0.0.0", "--port", "8000"]
